import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRef } from "react";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const print = () => window.print();
  // const print = () => {
  //   const printSectionRef = document.getElementById('printsection2');
  //   console.log(printSectionRef)
  //   if (printSectionRef) {
  //     const content = printSectionRef.innerHTML;
  //     // const newWindow = window.open('', '_blank');
 
  //     // newWindow.document.write(content);
  //     window.print();
  //     // window.close();
  //   }
  // };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>


      <main className={`${styles.main} ${styles.bodyy}`}>
        <h2 className={styles.h2}>hellow</h2>
        <h2 className={styles.h2}>hellow</h2>
        <h2 className={styles.h2}>hellow</h2>
        <h2 className={styles.h2}>hellow</h2>
        <h2 className={styles.h2}>hellow</h2>
        <h2 className={styles.h2}>hellow</h2>
        <h2 className={styles.h2}>hellow</h2>
        <h2 className={styles.h2}>hellow</h2>
        <h2 className={styles.h2}>hellow</h2>
        
        
        <button className={styles.btn} onClick={print}>Print</button>

        <div className={styles.printsection}
          id='printsection2' >
          <div className={styles.header}>Header content here</div> 

          <h3>
            <i>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis doloribus odio earum veritatis quaerat quibusdam consequatur numquam voluptate beatae necessitatibus! Eaque reprehenderit perspiciatis hic itaque totam sequi autem, et quibusdam!
            </i>  </h3>
          <h3>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis doloribus odio earum veritatis quaerat quibusdam consequatur numquam voluptate beatae necessitatibus! Eaque reprehenderit perspiciatis hic itaque totam sequi autem, et quibusdam!
          </h3>
          <h3>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis doloribus odio earum veritatis quaerat quibusdam consequatur numquam voluptate beatae necessitatibus! Eaque reprehenderit perspiciatis hic itaque totam sequi autem, et quibusdam!
          </h3>
          <h3>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis doloribus odio earum veritatis quaerat quibusdam consequatur numquam voluptate beatae necessitatibus! Eaque reprehenderit perspiciatis hic itaque totam sequi autem, et quibusdam!
          </h3>
          <h3>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis doloribus odio earum veritatis quaerat quibusdam consequatur numquam voluptate beatae necessitatibus! Eaque reprehenderit perspiciatis hic itaque totam sequi autem, et quibusdam!
          </h3>
          <h3>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis doloribus odio earum veritatis quaerat quibusdam consequatur numquam voluptate beatae necessitatibus! Eaque reprehenderit perspiciatis hic itaque totam sequi autem, et quibusdam!
          </h3>
          <h3>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis doloribus odio earum veritatis quaerat quibusdam consequatur numquam voluptate beatae necessitatibus! Eaque reprehenderit perspiciatis hic itaque totam sequi autem, et quibusdam!
          </h3>
          <h3>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis doloribus odio earum veritatis quaerat quibusdam consequatur numquam voluptate beatae necessitatibus! Eaque reprehenderit perspiciatis hic itaque totam sequi autem, et quibusdam!
          </h3>
          <h3>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis doloribus odio earum veritatis quaerat quibusdam consequatur numquam voluptate beatae necessitatibus! Eaque reprehenderit perspiciatis hic itaque totam sequi autem, et quibusdam!
          </h3>
          <h3>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis doloribus odio earum veritatis quaerat quibusdam consequatur numquam voluptate beatae necessitatibus! Eaque reprehenderit perspiciatis hic itaque totam sequi autem, et quibusdam!
          </h3>
          <h3>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis doloribus odio earum veritatis quaerat quibusdam consequatur numquam voluptate beatae necessitatibus! Eaque reprehenderit perspiciatis hic itaque totam sequi autem, et quibusdam!
          </h3>
          <h3>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis doloribus odio earum veritatis quaerat quibusdam consequatur numquam voluptate beatae necessitatibus! Eaque reprehenderit perspiciatis hic itaque totam sequi autem, et quibusdam!
          </h3>
          <h3>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis doloribus odio earum veritatis quaerat quibusdam consequatur numquam voluptate beatae necessitatibus! Eaque reprehenderit perspiciatis hic itaque totam sequi autem, et quibusdam!
          </h3>
          <h3>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis doloribus odio earum veritatis quaerat quibusdam consequatur numquam voluptate beatae necessitatibus! Eaque reprehenderit perspiciatis hic itaque totam sequi autem, et quibusdam!
          </h3>
          <h3>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis doloribus odio earum veritatis quaerat quibusdam consequatur numquam voluptate beatae necessitatibus! Eaque reprehenderit perspiciatis hic itaque totam sequi autem, et quibusdam!
          </h3>
          <h3>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis doloribus odio earum veritatis quaerat quibusdam consequatur numquam voluptate beatae necessitatibus! Eaque reprehenderit perspiciatis hic itaque totam sequi autem, et quibusdam!
          </h3>
          <h3>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis doloribus odio earum veritatis quaerat quibusdam consequatur numquam voluptate beatae necessitatibus! Eaque reprehenderit perspiciatis hic itaque totam sequi autem, et quibusdam!
          </h3>
          <h3>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis doloribus odio earum veritatis quaerat quibusdam consequatur numquam voluptate beatae necessitatibus! Eaque reprehenderit perspiciatis hic itaque totam sequi autem, et quibusdam!
          </h3>
          <h3>
            If you take the element that you want to be the footer and set it to be position:fixed and bottom:0, when the page prints it will repeat that element at the bottom of each printed page. The same would work for a header element, just set top:0 instead.

          </h3>
          <h3>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis doloribus odio earum veritatis quaerat quibusdam consequatur numquam voluptate beatae necessitatibus! Eaque reprehenderit perspiciatis hic itaque totam sequi autem, et quibusdam!
          </h3> 

          <div className={styles.footer}

          >
            Footer content here
          </div>
        </div>
        <h2 className={styles.h2}>hellow</h2>
        <h2 className={styles.h2}>hellow</h2>
      </main>



    </>
  )
}
